language: node_js
node_js:
  - stable
npm: true
cache:
  directories:
    - node_modules
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: pgJKiI7ZAFIkxdAUciOO4z5B6qjkEiYP8ZXfYCKny2tVe7FCcma0F3AWNYZS35la5fe3xsNuwc5TKdb/19SUL7h+eIbzgug2uQk+8RcLa0M29U7EdQVzNASyI7S9WXgakL2KIL11Uw4QgI9JpCuuFm0AZ2tXfB7aiVVRDjxGopUj2uy0mcf3G1lcrTAV+ra407E6o8cesQpY0DGF1xq15768wiHIQvrYyI9aB+xvpDMQ4XKMY3n6JrhN8zaB6oTJmvxw3f1QxWCq0OPLS0VjGCn0o0vgRVl/00CJiV5AC6A09DgAF94ikn9MEGZ4mhRT0+C7TZE9QnzREtdesHzajkiU2vGiQ+6Qn9TMZwSqff8hNOFtd4HKgB+2lP8zdlM4CqCG4qTdIM+2M99E1MdmLkcpXXhmVnHDujfvTXPUk6PGNI5VEFEhZflk6BEFekSAlZg1n1S6tCBhBgAkk735eLRyw9cfeC7LfT1e2Q7yWMudxb/RQPgBno3Ja4YvRq0asn8sBRtedDdcjIg/A3daiQTtGVAPgn3QhpVkAPHmIK74V5E1KNYfkX08NeNjurYmb3OvnhBOeh9lUKZOtuHVoZJsBTKKTX7RATqrMPb4kB5brwvYEn6tbyvVFqmqt78VGHFYx8a38OAl8xHpa5B5eppEZ6eh9E0VNeQUDM6SsGc=
  app: UofT_BootCamp_Project-2
  on:
    repo: saltamay/UofT_BootCamp_Project-2
