language: node_js
node_js:
  - stable
npm: true
env:
  - NODE_ENV=test
services:
  - mysql
cache:
  directories:
    - node_modules
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: YjUridM6AAMuApRnNlveo37psmMFbiiWag2opC+q141L4Ap3h+y7B/kcABZL3WSCg/JztoBJHyVjAlWwH+9dLHFE+dAzXG3Qvi34rAYCQuGNhJlUrGe49HGKtbZWRPH2Wof4KwlkyOW2ogdrnqV+D/wvA64lwN++Fi7jwc70hDQQ8UaEWQj1SeL8pyTklkvgJamiRfsM2GcsBmbQvHwfu2G0+kVLOk0OWJX5T00+qn3ZHG1jezIFpHCSMV4y9VGhzCK1xpVJ7PogEQ2gjMmzF25xJH4lDVanimd9zHijswspluIZlO7CvNZME5DmEacTvsXrvi8x3Z5VhCYQSMPautLAi0dfrtS5da4bxfw+6fJ3sO+I0wSAaVb8CRGopn0EFH0MyOa72gV52J+ZjLmNIS7mvKYqwFAveT3KV67gdap804126lDjjPb73QQOkRQbh/1Ga5LugsXyal6lWN+ZSZtxT5SPGt49skRarbAxZHwqd7hEnTMXZrJ7BepVxmnHWk3h6LO/RGZ5g6JWsjNYK5SmHDQWpv8GF6vatviTt04OTei7tSGJV9fyplElAZL9CtFtmBc04vq/Kkl96GJElCEoxsX6CuDB9NRZAoh75MpG4fDWPLiScM7+AoIJXwTDMqfi90gJgshIiDL6Odjgj7dTYsf119jlS8YGuRE/G/o=
  app: uoft-project2
  on:
    repo: saltamay/UofT_BootCamp_Project-2
